### PR TITLE
added capability to add interfaces to running containers

### LINKED ISSUE #252: add live interface attachement
allow users to add veth pairs on demand between two container. Can be a new command

```
clab connect <container-name>:<if-name> <container-name2>:<eth:if-name>
```

### PR DESCRIPTION
**Pull request by steiler**
This is a draft implementation for #252.

Issue the following to add a veth pair between wan1 and wan2.
`./containerlab tools connect containers  -t lab-examples/srl03/srl03.yml -a wan1:intf1 -b wan2:intf2 -m 1500`

Please have a look and provide feedback.
Cheers

close #252

### CODE REVIEW

**Comment by hellt** [comment]
Hey @steiler, thanks for looking into that one 

1. I had the following command name in my mind: `containerlab tools veth create -a $cont-name:$if-name -b ... -m`
2. do not depend on topo file to be available, make use of the functions to find the container by its name

**Comment by steiler** [comment]
Alright, removed the references to the topology file.
And also changed the command to the following:
`containerlab tools veth create -a clab-srl03-wan1:if1 -b clab-srl03-wan2:if2 -m 5000`

**Comment by hellt** [comment]
added support for host attachment as well

I will now add the docs and will merge this
Thank you for kickstarting and prototyping!

**Comment by alfonsomoneo** [comment]
Hello, I'm trying to create a new connection between 2 containers (2 Arista ceos 4.29.0) running in the same host but I doesn't work as expected. I don't get errors but after create the connetion, I access to devices and I new interfaces doesn't exist:

root@containerlab:/etc/containerlab/lab-examples/multi_fabric# containerlab tools veth create -a clab-backbone-backbone_11:Eth4 -b clab-fabric_pro_1-border_leaf_f1_11:Eth4 -m 9000
INFO[0000] Creating virtual wire: clab-backbone-backbone_11:Eth4 <--> clab-fabric_pro_1-border_leaf_f1_11:Eth4
INFO[0000] veth interface successfully created!

root@containerlab:/etc/containerlab/lab-examples/multi_fabric# docker exec -it clab-backbone-backbone_11 Cli
backbone_11>ena
backbone_11#show interfaces status
Port       Name                           Status       Vlan     Duplex Speed  Type            Flags Encapsulation
Et1        P2P_LINK_TO_SPINE1_Ethernet1/1 connected    routed   full   1G     EbraTestPhyPort
Et2        P2P_LINK_TO_SPINE2_Ethernet1/1 connected    routed   full   1G     EbraTestPhyPort
Et3                                       connected    routed   full   1G     EbraTestPhyPort
Ma0                                       connected    routed   a-full a-1G   10/100/1000

Can anybody help me. I may be doing something wrong.....

Thanks!

**Comment by hellt** [comment]
@alfonsomoneo It looks like arista might not support live interface attachments. probably you want to ask arista people if it is supported

**Comment by alfonsomoneo** [comment]
Thanks Helt, I will do it!

**Pull request merged**
