### PR TITLE
shell completions

### LINKED ISSUE #296: implement shell completions
for bash and zsh

### PR DESCRIPTION
**Pull request by steiler**
This is a very basic bash completion file. Which does not yet resolve any dynamic data.
There where discussions on keeping running topo files somewhere specific and so on, unfortunately I'm not on top of those discussions.
Hints on what / which parameters should be resolved dynamically are very welcome.

close #296

### CODE REVIEW

**Comment by hellt** [comment]
Thanks for helping, @steiler 
Can you maybe expore the functionality that cobra offers - https://github.com/spf13/cobra/blob/master/shell_completions.md?
This promises to generate completions on-the-fly for many shells

**Comment by steiler** [comment]
Alright, thanks for the hint.
Added the completion subcommand now.
However the dynamic file / folder and interface etc completion is to be introduced as well.

**Comment by hellt** [comment]
that looks good, thanks @steiler 
I will later add a doc in this PR and afterwards merge it

**Comment by hellt** [comment]
that looks good to me, merging

**Pull request merged**
